"""
Evidence relationship taxonomy constants — Phase 5.

Plain Python string constants, NOT database enum types.
Using plain strings avoids Alembic migrations when new types are added.

All values persisted to the database must come from these classes.
"""

from __future__ import annotations


class RelationshipType:
    """The nature of the directed edge between two evidence observations."""

    SAME_EVENT = "SAME_EVENT"
    """Both observations were produced by the same PaymentEvent (payment_event_id matches).
    This is the strongest possible source coupling: both facts emerged from a single
    webhook trigger in a single atomic extraction."""

    SAME_SOURCE = "SAME_SOURCE"
    """Both observations originate from the same WebhookEvent (webhook_event_id matches).
    Implies that the underlying provider signal is a single HTTP call, not two
    independent observations. SAME_SOURCE evidence must NOT be counted as independent."""

    SAME_PAYMENT = "SAME_PAYMENT"
    """Both observations describe the same payment (subject_type=payment, subject_id matches)."""

    SAME_ORDER = "SAME_ORDER"
    """Both observations describe the same order (subject_type=order, subject_id matches)."""

    DERIVED_FROM = "DERIVED_FROM"
    """Observation A is structurally derived from observation B.
    Example: PAYMENT_STATUS is derived from the PAYMENT_EVENT of the same event group.
    This is deterministic provenance, not statistical dependence."""

    DEPENDENT_ON = "DEPENDENT_ON"
    """Observation A depends on observation B for its meaning.
    Structurally identical to DERIVED_FROM at Phase 5 level; used when the
    derivation is more indirect (e.g. business-rule level rather than field-level)."""

    INDEPENDENCE_CANDIDATE = "INDEPENDENCE_CANDIDATE"
    """These observations originate from structurally distinct provider events
    (different webhook_event_id for the same payment subject).

    IMPORTANT: This is a heuristic structural label, NOT a proof of statistical
    independence. It means: 'these came from separate observation points and may
    contribute non-overlapping information.' Phase 5 does NOT assign independence scores.

    NEVER assigned to observations that share the same webhook_event_id (SAME_SOURCE).
    """

    TEMPORALLY_RELATED = "TEMPORALLY_RELATED"
    """Reserved for future phases. Two observations are adjacent in time."""

    CONTEXTUALLY_RELATED = "CONTEXTUALLY_RELATED"
    """Reserved for future phases. Two observations share a contextual signal
    that is not yet deterministically representable."""


class RelationshipSource:
    """How the relationship edge was produced."""

    DETERMINISTIC_RULE = "DETERMINISTIC_RULE"
    """Generated by a hardcoded, versioned, deterministic rule applied to
    existing evidence fields. The rule_version field identifies the exact logic."""

    PROVIDER_REFERENCE = "PROVIDER_REFERENCE"
    """Relationship asserted by the payment provider itself (e.g. Razorpay
    returns an explicit FK linking two entities)."""

    ENTITY_REFERENCE = "ENTITY_REFERENCE"
    """Relationship inferred from an FK already present in the relational schema
    (e.g. payment.order_id). Reserved for future entity-graph phases."""

    TEMPORAL_RULE = "TEMPORAL_RULE"
    """Generated from temporal proximity or ordering rules. Reserved."""

    MANUAL_REVIEW = "MANUAL_REVIEW"
    """Asserted by a human reviewer during investigation. Reserved."""


# Current version of the relationship rule logic.
# Increment this constant when any rule changes so that historical edges
# remain explainable by rule_version alone.
CURRENT_RELATIONSHIP_RULE_VERSION = "1.0"
