/**
 * Per-tab "what / how / why" copy rendered by <SectionIntro> at the top of
 * each view. Keyed by the same TabKey strings used in App.tsx.
 */

import type { SectionIntroProps } from '../components/SectionIntro'

export const SECTION_INTROS: Record<string, SectionIntroProps> = {
  live: {
    id: 'live',
    title: 'Live Event Stream',
    tagline: 'watch the pipeline process events in real time',
    kind: 'platform',
    what: 'A real-time feed of everything moving through EvidenceGraph — webhook deliveries, evidence observations, reconciled facts, and detected conflicts.',
    how: 'The browser holds one Server-Sent Events connection to the backend, which polls the database every 3 seconds and pushes only rows created since you connected. A periodic heartbeat keeps the connection proven-alive when nothing else is happening.',
    why: 'Makes the pipeline observable — you can watch a raw webhook arrive and become structured, verifiable evidence within seconds, instead of inferring it from logs.',
  },
  notifications: {
    id: 'notifications',
    title: 'Notification Center',
    tagline: 'every alert the system raises, in one inbox',
    kind: 'platform',
    what: 'A consolidated inbox of system notifications — fraud signals, payment-failure alerts, conflict warnings, and processing milestones — colour-coded by severity.',
    how: 'The backend emits typed notifications as the pipeline runs; this view fetches them and groups by severity and type.',
    why: 'One place to see what needs attention, rather than watching every dashboard separately.',
  },
  risk: {
    id: 'risk',
    title: 'Evidence Integrity Score',
    tagline: 'how solid is a payment’s evidence — analytical view only',
    kind: 'platform',
    what: 'An animated gauge of a payment’s composite evidence-integrity score, broken down by dimension: coverage, reliability, internal consistency, and provenance.',
    how: 'The Phase-9 integrity engine computes each dimension from the evidence graph; the gauge renders the overall score and its sub-scores as animated SVG.',
    why: 'A fast read on how much weight a payment’s evidence can bear. This is analytical only — the score never feeds the chargeback verdict, which stays fully deterministic.',
  },
  graph: {
    id: 'graph',
    title: 'Evidence Graph',
    tagline: 'the relationships between a payment’s evidence, visualised',
    kind: 'platform',
    what: 'An interactive force-directed map of one payment’s evidence — the payment at the centre, surrounded by its observations, sources, claims, and any conflicts.',
    how: 'A dependency-free canvas engine runs a physics simulation; hovering highlights a node’s neighbourhood, dragging pins a node, and the palette follows the light/dark theme.',
    why: 'Which facts corroborate, derive from, or contradict which — that structure is far easier to judge as a graph than as a table.',
  },
  fraud: {
    id: 'fraud',
    title: 'Fraud Pattern Detection',
    tagline: 'rule-based fraud signals — context, not a decision',
    kind: 'platform',
    what: 'A dashboard of fraud signals and cross-payment patterns surfaced by a deterministic rule engine — velocity, mismatch, and known-pattern checks.',
    how: 'Rules run over the evidence data and group hits by severity and pattern type; every hit links back to the evidence that triggered it.',
    why: 'Context for an investigator. Per Track-02 scope this is defense-only and read-only — nothing here decides a dispute or blocks a payment.',
  },
  failures: {
    id: 'failures',
    title: 'Payment Failure Intelligence',
    tagline: 'where and why authorisation is being lost',
    kind: 'platform',
    what: 'Root-cause breakdown of failed payments, funnel drop-off between stages, and failure-rate trends over time.',
    how: 'Failed payment events are bucketed by normalised failure reason and rendered as a funnel plus trend charts.',
    why: 'Distinguishes a gateway problem from a bank decline from customer drop-off — each needs a different fix.',
  },
  revenue: {
    id: 'revenue',
    title: 'Revenue Analytics',
    tagline: 'business baseline alongside the risk views',
    kind: 'platform',
    what: 'GMV, average transaction value, success rate, and time-series revenue trends.',
    how: 'Aggregates over the canonical payment records the platform has ingested.',
    why: 'Baseline context for the risk dashboards. Analytical only — outside the chargeback verifier.',
  },
  merchant: {
    id: 'merchant',
    title: 'Merchant Risk Profiling',
    tagline: 'which methods and corridors carry the risk — analytical view only',
    kind: 'platform',
    what: 'Risk profiling across payment dimensions — by method, by currency, by entity — with success rates and key risk indicators for each slice.',
    how: 'Groups evidence and outcome data by dimension and computes a comparative risk indicator per slice.',
    why: 'Highlights disproportionate risk in a payment method or corridor. Analytical only — not part of the verdict path.',
  },
  investigate: {
    id: 'investigate',
    title: 'Investigation Center',
    tagline: 'reconstruct exactly what happened, and in what order',
    kind: 'platform',
    what: 'Full-text search across every entity, a per-payment investigation profile, a unified timeline, and graph-traversal queries — provenance chains, claim support, conflict paths.',
    how: 'Search hits the indexed entity tables; the traversal endpoints run bounded breadth-first search over the persisted evidence relations, whitelisting out raw payloads and PII.',
    why: 'When a dispute lands, this is how you rebuild the sequence of events and trace every claim back to its sources.',
  },
  payments: {
    id: 'payments',
    title: 'Payment Inspector',
    tagline: 'the ground-truth view of a single payment',
    kind: 'platform',
    what: 'A per-payment inspector. Pick a payment from the row on top, then read it across three views — Overview (record, processing, consistency), Evidence (facts, claims, coverage, lineage) and Integrity & Replay.',
    how: 'Selecting a payment loads fourteen endpoints in parallel — events, evidence, facts, structure, consistency, integrity, coverage, lineage, reliability, evolution and replay — and lays each result out as its own panel.',
    why: 'The ground truth on one payment, grouped so you can answer one question at a time instead of scrolling one endless column.',
  },
  operations: {
    id: 'operations',
    title: 'Operational Intelligence',
    tagline: 'live proof the system is healthy and its guarantees hold',
    kind: 'platform',
    what: 'Live dependency health (DB, Redis, worker, pipeline), ingestion and processing metrics, an end-to-end pipeline view, and continuous checks of 10 formal system invariants.',
    how: 'Every figure is read from real runtime state on each load; the invariant checks re-run and report pass/fail with evidence. Nothing here is simulated.',
    why: 'Proves the system is actually healthy right now, and that its core guarantees — idempotency, temporal immutability, zero fabrication — still hold.',
  },
  defense: {
    id: 'defense',
    title: 'Defense Verification Evaluation',
    tagline: 'the measured Track-02 result on a held-out set',
    kind: 'deliverable',
    what: 'The evaluation harness — the 20-case frozen golden set of delivery disputes, the deterministic reference evaluator’s runs over it, and the resulting confusion matrix and per-class metrics.',
    how: 'Seed the dataset, run the evaluator, and every case is scored against its human label under a frozen train/test split: accuracy, macro-F1, per-class precision/recall, and the false-SUPPORTED count.',
    why: 'This is the measured evidence for the submission — ~90% accuracy, 0.885 macro-F1, 0 false-SUPPORTED, 100% contradiction recall, versus a 33% majority-class baseline.',
  },
  'defense-ai': {
    id: 'defense-ai',
    title: 'AI Defense Verifier',
    tagline: 'the model handles language; the deterministic core holds authority',
    kind: 'deliverable',
    what: 'Paste a merchant defense statement for a case and see the claims extracted, the evidence matched, and the deterministic verdict with its explanation — plus the three-way evaluation panel.',
    how: 'The AI layer (test stub by default; Anthropic / Mistral / OpenAI with a key) proposes claims and relevant evidence; the deterministic engine then decides, and can never be talked into SUPPORTED or out of a contradiction.',
    why: 'Shows the division of labour, and the three-way panel measures whether adding a real LLM actually helps accuracy or just adds false-support risk.',
  },
}
