"""Phase 3 Canonical Models

Revision ID: fe5fd3d3fd6f
Revises: 0001_phase2
Create Date: 2026-08-21 08:44:04.947191+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe5fd3d3fd6f'
down_revision: Union[str, None] = '0001_phase2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_references',
    sa.Column('internal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('razorpay_customer_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('internal_id')
    )
    op.create_index(op.f('ix_customer_references_razorpay_customer_id'), 'customer_references', ['razorpay_customer_id'], unique=True)
    op.create_table('orders',
    sa.Column('internal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='unknown', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('internal_id')
    )
    op.create_index(op.f('ix_orders_razorpay_order_id'), 'orders', ['razorpay_order_id'], unique=True)
    op.create_table('payments',
    sa.Column('internal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='unknown', nullable=False),
    sa.Column('payment_method_type', sa.String(length=32), nullable=True),
    sa.Column('payment_method_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('captured', sa.Boolean(), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_references.internal_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.internal_id'], ),
    sa.PrimaryKeyConstraint('internal_id')
    )
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['razorpay_payment_id'], unique=True)
    op.create_table('payment_events',
    sa.Column('internal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('webhook_event_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.internal_id'], ),
    sa.ForeignKeyConstraint(['webhook_event_id'], ['webhook_events.id'], ),
    sa.PrimaryKeyConstraint('internal_id')
    )
    op.create_index(op.f('ix_payment_events_payment_id'), 'payment_events', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_events_webhook_event_id'), 'payment_events', ['webhook_event_id'], unique=True)
    op.drop_index('ix_order_references_razorpay_order_id', table_name='order_references')
    op.drop_table('order_references')
    op.drop_index('ix_payment_references_razorpay_order_id', table_name='payment_references')
    op.drop_index('ix_payment_references_razorpay_payment_id', table_name='payment_references')
    op.drop_table('payment_references')
    op.drop_index('ix_webhook_events_event_type', table_name='webhook_events')
    op.drop_index('ix_webhook_events_order_id', table_name='webhook_events')
    op.drop_index('ix_webhook_events_payment_id', table_name='webhook_events')
    op.drop_index('ix_webhook_events_processing_status', table_name='webhook_events')
    op.drop_index('ix_webhook_events_received_at', table_name='webhook_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_webhook_events_received_at', 'webhook_events', ['received_at'], unique=False)
    op.create_index('ix_webhook_events_processing_status', 'webhook_events', ['processing_status'], unique=False)
    op.create_index('ix_webhook_events_payment_id', 'webhook_events', ['payment_id'], unique=False)
    op.create_index('ix_webhook_events_order_id', 'webhook_events', ['order_id'], unique=False)
    op.create_index('ix_webhook_events_event_type', 'webhook_events', ['event_type'], unique=False)
    op.create_table('payment_references',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('razorpay_payment_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('razorpay_order_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('latest_status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('event_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='payment_references_pkey'),
    sa.UniqueConstraint('razorpay_payment_id', name='payment_references_razorpay_payment_id_key')
    )
    op.create_index('ix_payment_references_razorpay_payment_id', 'payment_references', ['razorpay_payment_id'], unique=False)
    op.create_index('ix_payment_references_razorpay_order_id', 'payment_references', ['razorpay_order_id'], unique=False)
    op.create_table('order_references',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('razorpay_order_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('latest_status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('event_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='order_references_pkey'),
    sa.UniqueConstraint('razorpay_order_id', name='order_references_razorpay_order_id_key')
    )
    op.create_index('ix_order_references_razorpay_order_id', 'order_references', ['razorpay_order_id'], unique=False)
    op.drop_index(op.f('ix_payment_events_webhook_event_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_payment_id'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_orders_razorpay_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_customer_references_razorpay_customer_id'), table_name='customer_references')
    op.drop_table('customer_references')
    # ### end Alembic commands ###
